name: Build project with gradle and test

on:
  push:
    branches: [ "main", "cicd" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Build project with gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: current
      - name: Execute Gradle build
        run: gradle build --info --stacktrace
